# Generated by Django 3.1.1 on 2020-09-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_stripepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_products', to='cart.category'),
        ),
    ]
